# KISHU KUMAR
# 2105549
# CSE 24

In [1]:
import numpy

In [4]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
arr=[1,2,3,4,5]

print(type(arr))

<class 'list'>


In [6]:
import numpy as np
print(np.__version__)

1.24.3


In [13]:
import numpy as np
arr=np.array([1.4, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1.4 2.  3.  4.  5. ]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [10]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [12]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
import numpy as np
a=np.array(42)
b=np.array((1,2,3,4,5))
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [23]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("number of dimensions :",arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [49]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[4])

1
5


In [27]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[2]+arr[4])

8


In [30]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print("2 element of first row",arr[0,1])


2 element of first row 2


In [50]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5 element of second row",arr[1,4])


5 element of second row 10


In [33]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [35]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
10


In [53]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[1:5])

[2 3 4 5]


In [44]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [54]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [56]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])


[2 4]


In [57]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [60]:
import numpy as np
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
print(arr)

print(arr[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


In [62]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [67]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [72]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:1,1:4])

[[2 3 4]]


In [73]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [74]:
import numpy as np
arr=np.array(["apple","banana","cherry"])
print(arr.dtype)

<U6


In [79]:
import numpy as np
arr=np.array([1.2,2.3,3.4,4.5])
print(arr.dtype)
newarr=arr.astype(int)
print(arr)
print("after conversion")
print(newarr)
print(newarr.dtype)

float64
[1.2 2.3 3.4 4.5]
after conversion
[1 2 3 4]
int32


In [80]:
import numpy as np
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [81]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4]
[1 2 3 4]


In [82]:
import numpy as np
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4]
[42  2  3  4]


In [85]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [86]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [87]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(2,3,2))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [88]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
for i in arr:
    print(i)

1
2
3
4
5
6


In [89]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [6]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [101]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
arr=np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [100]:
import numpy as np
arr1=([[1,2],[2,4]])
arr2=([[5,6],[7,8]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [2 4 7 8]]


In [105]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarrnp=np.array_split(arr,3)
print(newarrnp)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [107]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


In [108]:
import numpy as np
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [111]:
import numpy as np
arr=np.array([1,2,3,4,5,4,7,4])
newarr=np.where(arr==4)
print(newarr)

(array([3, 5, 7], dtype=int64),)


In [112]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [113]:
import numpy as np
arr=np.array([1,6,4,5,7,2,9,])
x=np.sort(arr)
print(x)

[1 2 4 5 6 7 9]


In [114]:
import numpy as np
arr=np.array(["banana","cherry","apple"])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [115]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(np.sort(arr))

[[1 2 3]
 [4 5 6]]


In [116]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
x=np.mean(arr)
print(x)

5.0


In [117]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
x=np.median(arr)
print(x)

5.0


In [120]:
import numpy as np
from scipy import stats as st
arr=np.array([1,2,3,4,5,4,5,3,4,])
print(st.mode(arr))

ModeResult(mode=4, count=3)


In [122]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,end='\n\n')
print(arr.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [127]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,15,16,17,25,12])
arr=arr2-arr1
print(arr)

[ 9 13 13 13 20  6]


In [128]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,15,16,17,25,12])
arr=arr2+arr1
print(arr)

[11 17 19 21 30 18]


In [129]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,15,16,17,25,12])
arr=arr2*arr1
print(arr)

[ 10  30  48  68 125  72]


In [130]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,15,16,17,25,12])
arr=arr1/arr2
print(arr)

[0.1        0.13333333 0.1875     0.23529412 0.2        0.5       ]
