In [1]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [2]:
import sklearn

In [3]:
from sklearn import datasets
iris=datasets.load_iris()
print(iris.data.shape)

(150, 4)


In [5]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
feature_names=iris.feature_names
target_names=iris.target_names
print("Feature names:",feature_names)
print("Target names:",target_names)
print("\nfirst 10 rows of X:\n",x[:10])

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

first 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [7]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)
print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

(105, 4)
(45, 4)
(105,)
(45,)


In [11]:
#splitting datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(x_train, y_train)
y_pred = classifier_knn.predict(x_test)
print("Accuracy: ", metrics.accuracy_score(y_test, y_pred))
sample = [[5,5,3,2],[2,4,3,5]]
preds = classifier_knn.predict(sample)

Accuracy:  0.9777777777777777


In [1]:
#1
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target
# Display basic information
print(f"Number of samples: {X.shape}")
print(f"Number of features: {X.shape}")
print(f"Number of classes: {len(np.unique(y))}")

C:\Users\KIIT\anaconda3\Lib\site-packages\sklearn\datasets\_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


Number of samples: (70000, 784)
Number of features: (70000, 784)
Number of classes: 10


In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
clf = LogisticRegression(max_iter=1000, random_state=42)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: {accuracy:.4f}")

Test accuracy: 0.9667


In [3]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
iris_df = pd.DataFrame(X, columns=iris.feature_names)
iris_df['target'] = y
print(iris_df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.95


In [13]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.16.1


In [14]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 7s 1us/step


In [15]:
model = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(input_shape=(28, 28)),
 tf.keras.layers.Dense(128, activation='relu'),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10)
])

C:\Users\KIIT\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [16]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.015536  ,  0.65972817,  0.47529018,  0.18364045, -0.24778156,
        -0.09853665,  0.18455215, -0.02775241, -0.6471867 , -0.44358078]],
      dtype=float32)

In [17]:
tf.nn.softmax(predictions).numpy()

array([[0.09415357, 0.17931058, 0.14910956, 0.11138934, 0.07235681,
        0.08400317, 0.11149094, 0.09016477, 0.04853109, 0.05949014]],
      dtype=float32)

In [19]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

2.4769006

In [22]:
model.compile(optimizer='adam',
 loss=loss_fn,
 metrics=['accuracy'])

In [23]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8576 - loss: 0.4900
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9556 - loss: 0.1483
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9674 - loss: 0.1084
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9744 - loss: 0.0830
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9775 - loss: 0.0689


In [24]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 3ms/step - accuracy: 0.9766 - loss: 0.0763


[0.07625838369131088, 0.9765999913215637]

In [26]:
probability_model = tf.keras.Sequential([
 model,
 tf.keras.layers.Softmax()
])

In [27]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.80225996e-07, 2.40156197e-07, 4.89394188e-05, 3.46830435e-04,
        1.75892717e-10, 1.31927337e-07, 1.72810469e-13, 9.99588430e-01,
        1.02549677e-06, 1.41582468e-05],
       [6.25697094e-09, 5.14839542e-07, 9.99996781e-01, 2.39138194e-06,
        1.61059726e-15, 6.57221477e-08, 1.04954161e-08, 8.63346200e-12,
        1.79038011e-07, 2.90256697e-13],
       [3.70293861e-07, 9.99351323e-01, 8.94780460e-05, 1.20376289e-05,
        9.72808630e-06, 3.56701435e-06, 1.78022055e-05, 4.39828204e-04,
        7.38672315e-05, 2.05932088e-06],
       [9.99930620e-01, 3.13145456e-08, 1.76707726e-05, 6.58590977e-08,
        1.93199767e-07, 6.51613618e-07, 1.77722859e-06, 1.00365414e-05,
        1.33025271e-08, 3.88629342e-05],
       [2.28228714e-07, 1.44896575e-08, 2.02780338e-05, 1.91281089e-07,
        9.98590171e-01, 1.10147020e-08, 1.93102778e-07, 3.46889574e-05,
        8.37713799e-07, 1.35332532e-03]], dtype=float32)>